llm:
  provider: openai
  openai:
    api_key: null
    model: gpt-3.5-turbo
    temperature: 0.7
  llama:
    path_to_model: /path/to/model.bin
    max_tokens: 2048
stt:
  provider: whisper
  vosk:
    path_to_model: models/vosk-model-en-us-0.22
    sample_rate: 16000
    dtype: int16
    channels: 1
  whisper:
    size_model: tiny.en
    device: cpu
    compute_type: float32
    energy_threshold: 0.01
    min_duration: 0.3
    chunk_duration: 2
    sample_rate: 16000
    channels: 1
tts:
  provider: xtts
  elevenlabs:
    api_key: null
  xtts:
    model: tts_models/en/ljspeech/tacotron2-DDC
    vocoder_path: vocoder_models/en/ljspeech/hifigan_v2
    output_sample_rate: null
    min_word_duration: 0.1
    word_gap: 0.05
    sample_rate: 16000